cmake_minimum_required(VERSION 3.28)

set(CMAKE_SYSTEM_NAME GENERIC)
set(CMAKE_CROSSCOMPILING 1)

# Clang default install
set(RISCV_TOOL_PATH "/usr" CACHE PATH "RISC-V tool path")
set(RISCV_TOOL_PATH_BIN_DIR "${RISCV_TOOL_PATH}/bin")
set(RISCV_TOOLCHAIN_PREFIX "llvm")
set(RISCV_COMPLILER_PREFIX "${RISCV_TOOL_PATH_BIN_DIR}/${RISCV_TOOLCHAIN_PREFIX}")
set(RISCV_TOOLCHAIN_ROOT "${RISCV_TOOL_PATH}" CACHE PATH "RISC-V compiler path")

# Compiler, link, etc..
set(CMAKE_C_COMPILER "${RISCV_TOOLCHAIN_ROOT}/bin/clang")
set(CMAKE_CXX_COMPILER "${RISCV_TOOLCHAIN_ROOT}/bin/clang++")
set(CMAKE_AR "${RISCV_COMPLILER_PREFIX}-ar")
set(CMAKE_LINKER  "${RISCV_COMPLILER_PREFIX}-link")
set(CMAKE_RANLIB "${RISCV_COMPLILER_PREFIX}-ranlib")
set(CMAKE_NM "${RISCV_COMPLILER_PREFIX}-nm")
set(CMAKE_STRIP "${RISCV_COMPLILER_PREFIX}-strip")
set(CMAKE_SIZE "${RISCV_COMPLILER_PREFIX}-size")
set(CMAKE_OBJDUMP "${RISCV_COMPLILER_PREFIX}-objdump")
set(CMAKE_OBJCOPY "${RISCV_COMPLILER_PREFIX}-objcopy")
